### Leer sheets

In [12]:
import gspread
from google.colab import auth
import google.auth
import pandas as pd

auth.authenticate_user()

credentials, _ = google.auth.default(scopes=[
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
])

gc = gspread.authorize(credentials)

sheet_id = "1YMiaGVZER40nyDu11R1mFrawhS_wBQ2rs0e4iYB9qN4"
sheet_name = "Sheet1"

worksheet = gc.open_by_key(sheet_id).worksheet(sheet_name)
data = worksheet.get_all_values()
df_sheets_raw = pd.DataFrame(data[1:], columns=data[0])

df_sheets_raw.head()

,wave,analysis_group,franchise_id,franchise_name,vendor_code,store_name,city_name
0,1,Week32,treatment,None,None,369222,Avila Sushi
1,2,Week32,treatment,None,None,369222,Avila Sushi

In [13]:
query = '''
  SELECT
    l.peya_order_id,
    CAST(l.vendor.vendor_code AS STRING) AS vendor_code,
    COALESCE(l.vendor.name) AS store_name,
    l.city.city_name AS city_name,
  FROM `peya-bi-tools-pro.il_logistics.fact_logistic_orders` l
  LIMIT 5
  '''

In [14]:
project_id = 'peya-chile'

# Ejecuta la consulta en BigQuery y descarga los datos a Colab
df_query_raw = pd.read_gbq(query, project_id=project_id)

# Muestra las primeras 5 filas del resultado
df_query_raw.head()

/tmp/ipykernel_1453/1015631803.py:4: FutureWarning: read_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.read_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.read_gbq
  df_query_raw = pd.read_gbq(query, project_id=project_id)

   peya_order_id vendor_code                 store_name     city_name
0      406510838      277627             Cafeteria 0927      Barahona
1      406542389      278110          Mostaza Fast Food       La vega
2      406597430      279289            Bily Pica Pollo    Pedernales
3      406930788      102217        Mcdonald's Valdivia      Valdivia
4      406599589      267181  La Cocina Los Chiquitines  Monte cristi